### ISSUE TITLE
add datasets

### ISSUE THREAD

**Issue by samz5320** [samz5320/Data4ALL#1]
Add file in datasets folder and link it in index.html

**Comment by Abhijeet-Anand-01** [comment]
Hi Sanjay,
Can you please confirm that which all files are need to move in the datasets folder?
 
And please assign the task to me.
Thankyou!

**Comment by samz5320** [comment]
Add the csv or other format filesin the datasets folder.  which will be downloaded from the webpage.
and edit the same in index.html .

**Comment by ramya-neelakantan** [comment]
Can I add some datasets to this repo as a part of Hacktoberfest'21?

**Comment by samz5320** [comment]
can u link it also in the HTML? @ramya-neelakantan

**Comment by ramya-neelakantan** [comment]
> can u link it also in the HTML? @ramya-neelakantan

I'll do that... my dataset is a folder, which contains 6 categories of images, a readme for explanation and a csv file. Is there any particular method you want me to follow while adding the dataset?

**Comment by SahilSatyam** [comment]
Hey, please assign this task to me.

**Comment by ramya-neelakantan** [comment]
> > can u link it also in the HTML? @ramya-neelakantan
> 
> I'll do that... my dataset is a folder, which contains 6 categories of images, a readme for explanation and a csv file. Is there any particular method you want me to follow while adding the dataset?

also, please assign this task to me...

**Comment by samz5320** [comment]
> > can u link it also in the HTML? @ramya-neelakantan
> 
> I'll do that... my dataset is a folder, which contains 6 categories of images, a readme for explanation and a csv file. Is there any particular method you want me to follow while adding the dataset?

u can just put them in a folder. when it downloads it download as zip. like the folder in HTML .for downloading.

**Comment by samz5320** [comment]
This is issue is open to everyone :) as it is only an addition, no deletiion or changes might take place often.

**Comment by ramya-neelakantan** [comment]
I've added a dataset.. Please check

**Comment by AlphaLaser** [comment]
I added a Dataset - Reddit Vaccine Myths
