### ISSUE TITLE
Fix Copy link button 

### ISSUE THREAD

**Issue by samz5320** [samz5320/Data4ALL#11]

**Comment by rohan-kulkarni-25** [comment]
Can you Please Elaborate the issue @samz5320

**Comment by samz5320** [comment]
copy link has not been built. it needs to be made functional.. Onclick the link of that dataset should be copied to clipboard so we can paste It somewhere.

**Comment by rohan-kulkarni-25** [comment]
> copy link has not been built. it needs to be made functional.. Onclick the link of that dataset should be copied to clipboard so we can paste It somewhere.

Ohhk Cool but it will only work for Browsers on Desktop or PC on mobile this will not work I think

**Comment by RohanTheProgrammer** [comment]
@samz5320  Pls look into this PR
