### ISSUE TITLE
Add html file for beginner, intermediate and advanced

### ISSUE THREAD

**Issue by honeykpatel** [samz5320/Data4ALL#2]
Can add those 3 files and also some databases.

**Comment by samz5320** [comment]
i was thinking we could do it in the same page and add a search bar ?

**Comment by honeykpatel** [comment]
So something like on click and it scrolls to that section then?

**Comment by samz5320** [comment]
yup u can try that.

**Comment by honeykpatel** [comment]
I think we should close this one now.
