### ISSUE TITLE
Cursor->Hand-Pointer on hovering 'theme' and 'copy link' buttons

### ISSUE THREAD

**Issue by honeykpatel** [samz5320/Data4ALL#25]
When you hover to the button, cursor should change to pointer.
You have to add anchor tag to button.
I guess this would be a good first issue.

**Comment by Abhijeet-Anand-01** [comment]
> When you hover to the button, cursor should change to pointer. You have to add anchor tag to button. I guess this would be a good first issue.

Hello @honeykpatel, I've created a PR, can you please check it out and let me know that the output is as you desired!
And if not then please let me know for any further modifications.
Thanks :)

**Comment by Mr-vabs** [comment]
Can I work?

**Comment by Sameer1408** [comment]
hello @honeykpatel  sir I have  a bit experience of HTML and CSS may I work on it

**Comment by Sameer1408** [comment]
do we have to do this for every button or there is some specific one

**Comment by samz5320** [comment]
I think it's fixed already.. u can identify if there are any mistakes and let us know.

**Comment by akash391** [comment]
Sir please assign this issue to me as I know HTML, CSS and  will surely resolve it.

**Comment by Paawan9700** [comment]
hey, can you assign this issue to me as i have a much experience in HTML and CSS and i will put all my efforts to resolve it.

**Comment by samz5320** [comment]
Please read the above comments. U are open to finding any bugs or issues .drop in the description of the bug, and I'll assign it to you.

**Comment by honeykpatel** [comment]
Hey, @samz5320 I'm closing this issue as its becoming too spam-y!
