### ISSUE TITLE
add color coding [beginner,intermediate,advanced] to datasets in index.html

### ISSUE THREAD

**Issue by samz5320** [samz5320/Data4ALL#4]

**Comment by RohanTheProgrammer** [comment]
I would like to work on it. Is it in hacktoberfest because there is no tag in this issue.

**Comment by samz5320** [comment]
labels added :)

**Comment by RohanTheProgrammer** [comment]
I am working on it

**Comment by RohanTheProgrammer** [comment]
which datasets should I add to which category.

**Comment by RohanTheProgrammer** [comment]
1. ![Screenshot (32)](https://user-images.githubusercontent.com/48507690/135570144-bea0adf9-0ef9-4f34-8467-a77ca608a691.png)
2. ![Screenshot (33)](https://user-images.githubusercontent.com/48507690/135570147-45f508c3-871e-4f54-a4a7-fb032967d498.png)

I am thinking of 2. as styling, is it okay with you or you like something else

**Comment by samz5320** [comment]
if we could a bullet or a colored dot next to the dataset name?  also FYI there's a dark mode.

the level of difficulty of datasets we can figure out after we get some more.

**Comment by RohanTheProgrammer** [comment]
You have added Iris Dataset two times should I delete one.

BTW this is how it is looking now.
![Screenshot (34)](https://user-images.githubusercontent.com/48507690/135576636-c2c01f11-0858-4d0a-91e9-0dac8cd5d41a.png)
![Screenshot (35)](https://user-images.githubusercontent.com/48507690/135576639-c1acd8ac-45af-45bb-94bd-94c71c08d3b2.png)

**Comment by samz5320** [comment]
looks good. Yea iris that was just testing, u can delete the rightmost one.

**Comment by RohanTheProgrammer** [comment]
#13

**Comment by RohanTheProgrammer** [comment]
#13

**Comment by tanvideshmukh29** [comment]
I would love to contribute on this issue ...plz assign this to me.
