### ISSUE TITLE
Prettify Readme.md

### ISSUE THREAD

**Issue by samz5320** [samz5320/Data4ALL#6]

**Comment by SugatoBagchi** [comment]
Hey. I would like to work on this. Can you please assign it to me?

**Comment by samz5320** [comment]
Go Ahead .hv fun

**Comment by 2201monesh** [comment]
Hey @samz5320 I have updated the Readme.md have a look #21

**Comment by sudeepshukla930** [comment]
Hey @samz5320 , Can I redefine Readme ??

**Comment by samz5320** [comment]
> Hey @samz5320 , Can I redefine Readme ??

yup go ahead. 👍🏻

**Comment by jadhav-kunal** [comment]
Hey, I would also like to contribute and make readme more attractive. Could you please assign me?

**Comment by sudeepshukla930** [comment]
Hey @samz5320 ,
I have updated the Readme and created the pull request #62 
Please have a look  on it and accept it with **"hacktoberfest2021 accepted"** label
Thankyou
