### ISSUE TITLE
Display 'copied' notification after copy is clicked

### ISSUE THREAD

**Issue by Khushi-Shukla** [samz5320/Data4ALL#60]
When the copy link button is clicked, a confirmation that the link has been copied should be displayed.

**Comment by Khushi-Shukla** [comment]
Kindly assign this issue to me

**Comment by Khushi-Shukla** [comment]
@samz5320 I worked on this issue such that the text inside the button becomes 'copied' for one second and then changes back to 'copy link' i.e., the original text 
![image](https://user-images.githubusercontent.com/55341533/135730519-a01ac22e-94b1-4713-ba57-4e82fa51a2b8.png)
![image](https://user-images.githubusercontent.com/55341533/135730529-3201ee6b-702d-4110-bbc3-f8b13384583b.png)
Can I open a PR for this code?

**Comment by coder483** [comment]
hey i fixed this

**Comment by coder483** [comment]
fixed 'copied' notification after copy is clicked #72 please check it

**Comment by coder483** [comment]
sorry forget the screenshot
![caputre1](https://user-images.githubusercontent.com/77922584/135742400-8e5a0ea1-a9dd-43c0-9e91-fcd22c91dbe2.PNG)

**Comment by coder483** [comment]
after the solve
![Capture2](https://user-images.githubusercontent.com/77922584/135742416-02bcd635-7fd3-49bf-b326-08bea89209ad.PNG)

**Comment by rohan9024** [comment]
Can I work on this Issue for Hactoberfest 2021?

**Comment by Khushi-Shukla** [comment]
I raised this issue so that I can work on it and have also submitted a PR.  Only the owner can merge the PR

**Comment by samz5320** [comment]
Please wait to get it assigned before sending a PR.  There will be conflicts in files if I do not accept PRs in order.

**Comment by Khushi-Shukla** [comment]
Can you assign this issue to me? Then I can send a PR again

**Comment by Priyanshi-Raj** [comment]
Can you please assign me this task.

**Comment by samz5320** [comment]
sry, issues closed. Features have been implemented and merged.
